name: Java CI

on: [push]

permissions: ## https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
  id-token: write
  contents: read
  issues: write
  pull-requests: write
  checks: write  ## fixed an Error: HttpError: Resource not accessible by integration: https://github.com/dorny/test-reporter/issues/149#issuecomment-1004820190

## Build gradle project
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  ## downloads a copy of your repository on the runner.
      - name: Set up JDK 11
        uses: actions/setup-java@v3 ## configures the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Report ## https://octopus.com/blog/githubactions-running-unit-tests
        uses: dorny/test-reporter@v1
        if: always() ## generate the report even if the Test step above was set to fail in the event of failed tests.
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Publish Sonarlint Results ## https://www.linkedin.com/pulse/static-code-analysis-sonarlint-github-actions-lucas-persson/
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          name: Sonarlint
          title: Sonarlint report
          path: build/reports/sonarlint/*.xml
      - name: Publish Spotbugs Results
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          name: Spotbugs
          path: build/reports/spotbugs/*.xml